name: ds_assets
description: "Design System Assets"
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

flutter:
  assets:
    - assets/photos/
    - assets/resources/